version: "3.6"
services:
  ttrss-data:
    image: nornagon/postgres
    container_name: ttrss-data
    volumes:
      - data:/var/lib/postgresql/data
    restart: always
    network_mode: bridge

  ttrss:
    image: karronqiu/docker-ttrss
    container_name: ttrss
    ports:
      - "8080:8080/tcp"
    links:
      - ttrss-data:db
    environment:
      - TTRSS_SELF_URL=http://localhost:8080/
      - TTRSS_PORT=8080
    restart: always
    network_mode: bridge

volumes:
  data:
